### ISSUE TITLE
Make the Q7.java file as follows

### ISSUE THREAD

**Issue by jyothi-1822** [jyothi-1822/Samplejava#1]
Write a Java program to implement voting in SAC elections and display the results with the support of interfaces. Create a class ElectionPost, which has attributes nameOfthePost (String), listOfCandidates (ArrayList of String) and votesEntered (ArrayList of String). There is a displaymethod in the class which displays the name of the post and the election candidate’s name (in
Ascending order of their name). There is an interface SortVotes which has two methods
ascendDisplay and descendDisplay which should be implemented in the class to display the
details by sorting the candidates according to their count of votes in ascending order and
descending order respectively.

**Comment by vasanthkumar18** [comment]
I'd like to solve this issue
